//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.IRISCDCService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cdc:iisb:2011")]
    public partial class soapFaultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string reasonField;
        
        private string detailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("Detail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cdc:iisb:2011")]
    public partial class UnsupportedOperationFaultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private object reasonField;
        
        private string detailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='UnsupportedOperation' attribute.
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("Detail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cdc:iisb:2011")]
    public partial class SecurityFaultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private object reasonField;
        
        private string detailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='Security' attribute.
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("Detail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cdc:iisb:2011")]
    public partial class MessageTooLargeFaultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private object reasonField;
        
        private string detailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='MessageTooLarge' attribute.
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("Detail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:cdc:iisb:2011", ConfigurationName="IRISCDCService.IIS_PortType")]
    public interface IIS_PortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:cdc:iisb:2011:connectivityTest", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApp1.IRISCDCService.soapFaultType), Action="urn:cdc:iisb:2011:connectivityTest", Name="fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApp1.IRISCDCService.UnsupportedOperationFaultType), Action="urn:cdc:iisb:2011:connectivityTest", Name="UnsupportedOperationFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApp1.IRISCDCService.connectivityTestResponse connectivityTest(ConsoleApp1.IRISCDCService.connectivityTestRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:cdc:iisb:2011:submitSingleMessage", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApp1.IRISCDCService.soapFaultType), Action="urn:cdc:iisb:2011:submitSingleMessage", Name="fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApp1.IRISCDCService.SecurityFaultType), Action="urn:cdc:iisb:2011:submitSingleMessage", Name="SecurityFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApp1.IRISCDCService.MessageTooLargeFaultType), Action="urn:cdc:iisb:2011:submitSingleMessage", Name="MessageTooLargeFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApp1.IRISCDCService.submitSingleMessageResponse submitSingleMessage(ConsoleApp1.IRISCDCService.submitSingleMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="connectivityTest", WrapperNamespace="urn:cdc:iisb:2011", IsWrapped=true)]
    public partial class connectivityTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:cdc:iisb:2011", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string echoBack;
        
        public connectivityTestRequest() {
        }
        
        public connectivityTestRequest(string echoBack) {
            this.echoBack = echoBack;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="connectivityTestResponse", WrapperNamespace="urn:cdc:iisb:2011", IsWrapped=true)]
    public partial class connectivityTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:cdc:iisb:2011", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public connectivityTestResponse() {
        }
        
        public connectivityTestResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="submitSingleMessage", WrapperNamespace="urn:cdc:iisb:2011", IsWrapped=true)]
    public partial class submitSingleMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:cdc:iisb:2011", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:cdc:iisb:2011", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:cdc:iisb:2011", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string facilityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:cdc:iisb:2011", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string hl7Message;
        
        public submitSingleMessageRequest() {
        }
        
        public submitSingleMessageRequest(string username, string password, string facilityID, string hl7Message) {
            this.username = username;
            this.password = password;
            this.facilityID = facilityID;
            this.hl7Message = hl7Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="submitSingleMessageResponse", WrapperNamespace="urn:cdc:iisb:2011", IsWrapped=true)]
    public partial class submitSingleMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:cdc:iisb:2011", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public submitSingleMessageResponse() {
        }
        
        public submitSingleMessageResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIS_PortTypeChannel : ConsoleApp1.IRISCDCService.IIS_PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IS_PortTypeClient : System.ServiceModel.ClientBase<ConsoleApp1.IRISCDCService.IIS_PortType>, ConsoleApp1.IRISCDCService.IIS_PortType {
        
        public IS_PortTypeClient() {
        }
        
        public IS_PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IS_PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IS_PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IS_PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.IRISCDCService.connectivityTestResponse ConsoleApp1.IRISCDCService.IIS_PortType.connectivityTest(ConsoleApp1.IRISCDCService.connectivityTestRequest request) {
            return base.Channel.connectivityTest(request);
        }
        
        public string connectivityTest(string echoBack) {
            ConsoleApp1.IRISCDCService.connectivityTestRequest inValue = new ConsoleApp1.IRISCDCService.connectivityTestRequest();
            inValue.echoBack = echoBack;
            ConsoleApp1.IRISCDCService.connectivityTestResponse retVal = ((ConsoleApp1.IRISCDCService.IIS_PortType)(this)).connectivityTest(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.IRISCDCService.submitSingleMessageResponse ConsoleApp1.IRISCDCService.IIS_PortType.submitSingleMessage(ConsoleApp1.IRISCDCService.submitSingleMessageRequest request) {
            return base.Channel.submitSingleMessage(request);
        }
        
        public string submitSingleMessage(string username, string password, string facilityID, string hl7Message) {
            ConsoleApp1.IRISCDCService.submitSingleMessageRequest inValue = new ConsoleApp1.IRISCDCService.submitSingleMessageRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.facilityID = facilityID;
            inValue.hl7Message = hl7Message;
            ConsoleApp1.IRISCDCService.submitSingleMessageResponse retVal = ((ConsoleApp1.IRISCDCService.IIS_PortType)(this)).submitSingleMessage(inValue);
            return retVal.@return;
        }
    }
}
