//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.SMVDHSSMO {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS", ConfigurationName="SMVDHSSMO.ProviderInterface_EXTSoap")]
    public interface ProviderInterface_EXTSoap {
        
        // CODEGEN: Generating message contract since the wrapper name (SMVHL7VAL_PLAIN_x0028__x0029_) of message SMVHL7VAL_PLAIN_x0028__x0029_ does not match the default value (SMVHL7VAL_PLAIN)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS/SMVHL7" +
            "VAL_PLAIN()", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApp1.SMVDHSSMO.SMVHL7VAL_PLAIN1 SMVHL7VAL_PLAIN(ConsoleApp1.SMVDHSSMO.SMVHL7VAL_PLAIN request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS/SMVHL7" +
            "VAL_PLAIN()", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.SMVDHSSMO.SMVHL7VAL_PLAIN1> SMVHL7VAL_PLAINAsync(ConsoleApp1.SMVDHSSMO.SMVHL7VAL_PLAIN request);
        
        // CODEGEN: Generating message contract since the wrapper name (SMVHL7VAL_x0028__x0029_) of message SMVHL7VAL_x0028__x0029_ does not match the default value (SMVHL7VAL)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS/SMVHL7" +
            "VAL()", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApp1.SMVDHSSMO.SMVHL7VAL1 SMVHL7VAL(ConsoleApp1.SMVDHSSMO.SMVHL7VAL request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS/SMVHL7" +
            "VAL()", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.SMVDHSSMO.SMVHL7VAL1> SMVHL7VALAsync(ConsoleApp1.SMVDHSSMO.SMVHL7VAL request);
        
        // CODEGEN: Generating message contract since the wrapper name (SMVHL7_PLAIN_x0028__x0029_) of message SMVHL7_PLAIN_x0028__x0029_ does not match the default value (SMVHL7_PLAIN)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS/SMVHL7" +
            "_PLAIN()", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApp1.SMVDHSSMO.SMVHL7_PLAIN1 SMVHL7_PLAIN(ConsoleApp1.SMVDHSSMO.SMVHL7_PLAIN request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS/SMVHL7" +
            "_PLAIN()", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.SMVDHSSMO.SMVHL7_PLAIN1> SMVHL7_PLAINAsync(ConsoleApp1.SMVDHSSMO.SMVHL7_PLAIN request);
        
        // CODEGEN: Generating message contract since the wrapper name (SMVHL7_x0028__x0029_) of message SMVHL7_x0028__x0029_ does not match the default value (SMVHL7)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS/SMVHL7" +
            "()", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApp1.SMVDHSSMO.SMVHL71 SMVHL7(ConsoleApp1.SMVDHSSMO.SMVHL7 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS/SMVHL7" +
            "()", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.SMVDHSSMO.SMVHL71> SMVHL7Async(ConsoleApp1.SMVDHSSMO.SMVHL7 request);
        
        // CODEGEN: Generating message contract since the wrapper name (VXU_Validation_x0028__x0029_) of message VXU_Validation_x0028__x0029_ does not match the default value (VXU_Validation)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS/VXU_Va" +
            "lidation()", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApp1.SMVDHSSMO.VXU_Validation1 VXU_Validation(ConsoleApp1.SMVDHSSMO.VXU_Validation request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS/VXU_Va" +
            "lidation()", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.SMVDHSSMO.VXU_Validation1> VXU_ValidationAsync(ConsoleApp1.SMVDHSSMO.VXU_Validation request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SMVHL7VAL_PLAIN()", WrapperNamespace="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS", IsWrapped=true)]
    public partial class SMVHL7VAL_PLAIN {
        
        public SMVHL7VAL_PLAIN() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SMVHL7VAL_PLAIN()Response", WrapperNamespace="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS", IsWrapped=true)]
    public partial class SMVHL7VAL_PLAIN1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SMVHL7VAL_PLAIN()Result")]
        public string SMVHL7VAL_PLAINResult;
        
        public SMVHL7VAL_PLAIN1() {
        }
        
        public SMVHL7VAL_PLAIN1(string SMVHL7VAL_PLAINResult) {
            this.SMVHL7VAL_PLAINResult = SMVHL7VAL_PLAINResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS")]
    public partial class HL7SoapHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uSERIDField;
        
        private string pASSWORD1Field;
        
        private string pASSWORD2Field;
        
        private string fACILITYIDField;
        
        private string mESSAGEDATAField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string USERID {
            get {
                return this.uSERIDField;
            }
            set {
                this.uSERIDField = value;
                this.RaisePropertyChanged("USERID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PASSWORD1 {
            get {
                return this.pASSWORD1Field;
            }
            set {
                this.pASSWORD1Field = value;
                this.RaisePropertyChanged("PASSWORD1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PASSWORD2 {
            get {
                return this.pASSWORD2Field;
            }
            set {
                this.pASSWORD2Field = value;
                this.RaisePropertyChanged("PASSWORD2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FACILITYID {
            get {
                return this.fACILITYIDField;
            }
            set {
                this.fACILITYIDField = value;
                this.RaisePropertyChanged("FACILITYID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MESSAGEDATA {
            get {
                return this.mESSAGEDATAField;
            }
            set {
                this.mESSAGEDATAField = value;
                this.RaisePropertyChanged("MESSAGEDATA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS")]
    public partial class HL7_Validation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fACILITYIDField;
        
        private string mESSAGEDATAField;
        
        private string eRRORSField;
        
        private bool iSVALIDField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FACILITYID {
            get {
                return this.fACILITYIDField;
            }
            set {
                this.fACILITYIDField = value;
                this.RaisePropertyChanged("FACILITYID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MESSAGEDATA {
            get {
                return this.mESSAGEDATAField;
            }
            set {
                this.mESSAGEDATAField = value;
                this.RaisePropertyChanged("MESSAGEDATA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ERRORS {
            get {
                return this.eRRORSField;
            }
            set {
                this.eRRORSField = value;
                this.RaisePropertyChanged("ERRORS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool ISVALID {
            get {
                return this.iSVALIDField;
            }
            set {
                this.iSVALIDField = value;
                this.RaisePropertyChanged("ISVALID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SMVHL7VAL()", WrapperNamespace="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS", IsWrapped=true)]
    public partial class SMVHL7VAL {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS")]
        public ConsoleApp1.SMVDHSSMO.HL7SoapHeader HL7SoapHeader;
        
        public SMVHL7VAL() {
        }
        
        public SMVHL7VAL(ConsoleApp1.SMVDHSSMO.HL7SoapHeader HL7SoapHeader) {
            this.HL7SoapHeader = HL7SoapHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SMVHL7VAL()Response", WrapperNamespace="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS", IsWrapped=true)]
    public partial class SMVHL7VAL1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SMVHL7VAL()Result")]
        public string SMVHL7VALResult;
        
        public SMVHL7VAL1() {
        }
        
        public SMVHL7VAL1(string SMVHL7VALResult) {
            this.SMVHL7VALResult = SMVHL7VALResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SMVHL7_PLAIN()", WrapperNamespace="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS", IsWrapped=true)]
    public partial class SMVHL7_PLAIN {
        
        public SMVHL7_PLAIN() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SMVHL7_PLAIN()Response", WrapperNamespace="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS", IsWrapped=true)]
    public partial class SMVHL7_PLAIN1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SMVHL7_PLAIN()Result")]
        public string SMVHL7_PLAINResult;
        
        public SMVHL7_PLAIN1() {
        }
        
        public SMVHL7_PLAIN1(string SMVHL7_PLAINResult) {
            this.SMVHL7_PLAINResult = SMVHL7_PLAINResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SMVHL7()", WrapperNamespace="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS", IsWrapped=true)]
    public partial class SMVHL7 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS")]
        public ConsoleApp1.SMVDHSSMO.HL7SoapHeader HL7SoapHeader;
        
        public SMVHL7() {
        }
        
        public SMVHL7(ConsoleApp1.SMVDHSSMO.HL7SoapHeader HL7SoapHeader) {
            this.HL7SoapHeader = HL7SoapHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SMVHL7()Response", WrapperNamespace="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS", IsWrapped=true)]
    public partial class SMVHL71 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SMVHL7()Result")]
        public string SMVHL7Result;
        
        public SMVHL71() {
        }
        
        public SMVHL71(string SMVHL7Result) {
            this.SMVHL7Result = SMVHL7Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VXU_Validation()", WrapperNamespace="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS", IsWrapped=true)]
    public partial class VXU_Validation {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS")]
        public ConsoleApp1.SMVDHSSMO.HL7_Validation HL7_Validation;
        
        public VXU_Validation() {
        }
        
        public VXU_Validation(ConsoleApp1.SMVDHSSMO.HL7_Validation HL7_Validation) {
            this.HL7_Validation = HL7_Validation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VXU_Validation()Response", WrapperNamespace="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS", IsWrapped=true)]
    public partial class VXU_Validation1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/SMVAX_ProviderInterface_EXT_WS/ProviderInterface_EXT_WS", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("VXU_Validation()Result")]
        public string VXU_ValidationResult;
        
        public VXU_Validation1() {
        }
        
        public VXU_Validation1(string VXU_ValidationResult) {
            this.VXU_ValidationResult = VXU_ValidationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProviderInterface_EXTSoapChannel : ConsoleApp1.SMVDHSSMO.ProviderInterface_EXTSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProviderInterface_EXTSoapClient : System.ServiceModel.ClientBase<ConsoleApp1.SMVDHSSMO.ProviderInterface_EXTSoap>, ConsoleApp1.SMVDHSSMO.ProviderInterface_EXTSoap {
        
        public ProviderInterface_EXTSoapClient() {
        }
        
        public ProviderInterface_EXTSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProviderInterface_EXTSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProviderInterface_EXTSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProviderInterface_EXTSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.SMVDHSSMO.SMVHL7VAL_PLAIN1 ConsoleApp1.SMVDHSSMO.ProviderInterface_EXTSoap.SMVHL7VAL_PLAIN(ConsoleApp1.SMVDHSSMO.SMVHL7VAL_PLAIN request) {
            return base.Channel.SMVHL7VAL_PLAIN(request);
        }
        
        public string SMVHL7VAL_PLAIN() {
            ConsoleApp1.SMVDHSSMO.SMVHL7VAL_PLAIN inValue = new ConsoleApp1.SMVDHSSMO.SMVHL7VAL_PLAIN();
            ConsoleApp1.SMVDHSSMO.SMVHL7VAL_PLAIN1 retVal = ((ConsoleApp1.SMVDHSSMO.ProviderInterface_EXTSoap)(this)).SMVHL7VAL_PLAIN(inValue);
            return retVal.SMVHL7VAL_PLAINResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.SMVDHSSMO.SMVHL7VAL_PLAIN1> ConsoleApp1.SMVDHSSMO.ProviderInterface_EXTSoap.SMVHL7VAL_PLAINAsync(ConsoleApp1.SMVDHSSMO.SMVHL7VAL_PLAIN request) {
            return base.Channel.SMVHL7VAL_PLAINAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.SMVDHSSMO.SMVHL7VAL_PLAIN1> SMVHL7VAL_PLAINAsync() {
            ConsoleApp1.SMVDHSSMO.SMVHL7VAL_PLAIN inValue = new ConsoleApp1.SMVDHSSMO.SMVHL7VAL_PLAIN();
            return ((ConsoleApp1.SMVDHSSMO.ProviderInterface_EXTSoap)(this)).SMVHL7VAL_PLAINAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.SMVDHSSMO.SMVHL7VAL1 ConsoleApp1.SMVDHSSMO.ProviderInterface_EXTSoap.SMVHL7VAL(ConsoleApp1.SMVDHSSMO.SMVHL7VAL request) {
            return base.Channel.SMVHL7VAL(request);
        }
        
        public string SMVHL7VAL(ConsoleApp1.SMVDHSSMO.HL7SoapHeader HL7SoapHeader) {
            ConsoleApp1.SMVDHSSMO.SMVHL7VAL inValue = new ConsoleApp1.SMVDHSSMO.SMVHL7VAL();
            inValue.HL7SoapHeader = HL7SoapHeader;
            ConsoleApp1.SMVDHSSMO.SMVHL7VAL1 retVal = ((ConsoleApp1.SMVDHSSMO.ProviderInterface_EXTSoap)(this)).SMVHL7VAL(inValue);
            return retVal.SMVHL7VALResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.SMVDHSSMO.SMVHL7VAL1> ConsoleApp1.SMVDHSSMO.ProviderInterface_EXTSoap.SMVHL7VALAsync(ConsoleApp1.SMVDHSSMO.SMVHL7VAL request) {
            return base.Channel.SMVHL7VALAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.SMVDHSSMO.SMVHL7VAL1> SMVHL7VALAsync(ConsoleApp1.SMVDHSSMO.HL7SoapHeader HL7SoapHeader) {
            ConsoleApp1.SMVDHSSMO.SMVHL7VAL inValue = new ConsoleApp1.SMVDHSSMO.SMVHL7VAL();
            inValue.HL7SoapHeader = HL7SoapHeader;
            return ((ConsoleApp1.SMVDHSSMO.ProviderInterface_EXTSoap)(this)).SMVHL7VALAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.SMVDHSSMO.SMVHL7_PLAIN1 ConsoleApp1.SMVDHSSMO.ProviderInterface_EXTSoap.SMVHL7_PLAIN(ConsoleApp1.SMVDHSSMO.SMVHL7_PLAIN request) {
            return base.Channel.SMVHL7_PLAIN(request);
        }
        
        public string SMVHL7_PLAIN() {
            ConsoleApp1.SMVDHSSMO.SMVHL7_PLAIN inValue = new ConsoleApp1.SMVDHSSMO.SMVHL7_PLAIN();
            ConsoleApp1.SMVDHSSMO.SMVHL7_PLAIN1 retVal = ((ConsoleApp1.SMVDHSSMO.ProviderInterface_EXTSoap)(this)).SMVHL7_PLAIN(inValue);
            return retVal.SMVHL7_PLAINResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.SMVDHSSMO.SMVHL7_PLAIN1> ConsoleApp1.SMVDHSSMO.ProviderInterface_EXTSoap.SMVHL7_PLAINAsync(ConsoleApp1.SMVDHSSMO.SMVHL7_PLAIN request) {
            return base.Channel.SMVHL7_PLAINAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.SMVDHSSMO.SMVHL7_PLAIN1> SMVHL7_PLAINAsync() {
            ConsoleApp1.SMVDHSSMO.SMVHL7_PLAIN inValue = new ConsoleApp1.SMVDHSSMO.SMVHL7_PLAIN();
            return ((ConsoleApp1.SMVDHSSMO.ProviderInterface_EXTSoap)(this)).SMVHL7_PLAINAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.SMVDHSSMO.SMVHL71 ConsoleApp1.SMVDHSSMO.ProviderInterface_EXTSoap.SMVHL7(ConsoleApp1.SMVDHSSMO.SMVHL7 request) {
            return base.Channel.SMVHL7(request);
        }
        
        public string SMVHL7(ConsoleApp1.SMVDHSSMO.HL7SoapHeader HL7SoapHeader) {
            ConsoleApp1.SMVDHSSMO.SMVHL7 inValue = new ConsoleApp1.SMVDHSSMO.SMVHL7();
            inValue.HL7SoapHeader = HL7SoapHeader;
            ConsoleApp1.SMVDHSSMO.SMVHL71 retVal = ((ConsoleApp1.SMVDHSSMO.ProviderInterface_EXTSoap)(this)).SMVHL7(inValue);
            return retVal.SMVHL7Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.SMVDHSSMO.SMVHL71> ConsoleApp1.SMVDHSSMO.ProviderInterface_EXTSoap.SMVHL7Async(ConsoleApp1.SMVDHSSMO.SMVHL7 request) {
            return base.Channel.SMVHL7Async(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.SMVDHSSMO.SMVHL71> SMVHL7Async(ConsoleApp1.SMVDHSSMO.HL7SoapHeader HL7SoapHeader) {
            ConsoleApp1.SMVDHSSMO.SMVHL7 inValue = new ConsoleApp1.SMVDHSSMO.SMVHL7();
            inValue.HL7SoapHeader = HL7SoapHeader;
            return ((ConsoleApp1.SMVDHSSMO.ProviderInterface_EXTSoap)(this)).SMVHL7Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.SMVDHSSMO.VXU_Validation1 ConsoleApp1.SMVDHSSMO.ProviderInterface_EXTSoap.VXU_Validation(ConsoleApp1.SMVDHSSMO.VXU_Validation request) {
            return base.Channel.VXU_Validation(request);
        }
        
        public string VXU_Validation(ConsoleApp1.SMVDHSSMO.HL7_Validation HL7_Validation) {
            ConsoleApp1.SMVDHSSMO.VXU_Validation inValue = new ConsoleApp1.SMVDHSSMO.VXU_Validation();
            inValue.HL7_Validation = HL7_Validation;
            ConsoleApp1.SMVDHSSMO.VXU_Validation1 retVal = ((ConsoleApp1.SMVDHSSMO.ProviderInterface_EXTSoap)(this)).VXU_Validation(inValue);
            return retVal.VXU_ValidationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.SMVDHSSMO.VXU_Validation1> ConsoleApp1.SMVDHSSMO.ProviderInterface_EXTSoap.VXU_ValidationAsync(ConsoleApp1.SMVDHSSMO.VXU_Validation request) {
            return base.Channel.VXU_ValidationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.SMVDHSSMO.VXU_Validation1> VXU_ValidationAsync(ConsoleApp1.SMVDHSSMO.HL7_Validation HL7_Validation) {
            ConsoleApp1.SMVDHSSMO.VXU_Validation inValue = new ConsoleApp1.SMVDHSSMO.VXU_Validation();
            inValue.HL7_Validation = HL7_Validation;
            return ((ConsoleApp1.SMVDHSSMO.ProviderInterface_EXTSoap)(this)).VXU_ValidationAsync(inValue);
        }
    }
}
